version: "3"

services:
  backend:
    build: ./
    container_name: volunteering_hub
    working_dir: /hub
    command:
      - ./start_server.sh
    ports:
      - "8000:8000"
    volumes:
      - ./src:/hub/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_admin
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres

  mongodb:
    image: mongo:3-stretch
    container_name: mongo_db
    ports:
      - "27017:27017"
    command: [ "--bind_ip_all", "--smallfiles" ]
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    restart: always

  mongoadmin:
    image: mongo-express
    container_name: mongo_admin
    ports:
      - "8081:8081"
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: always



volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  pgadmin_data: { }
  mongo_data: { }