version: "3"

services:
  backend:
    build: ./
    container_name: vol_hub
    working_dir: /hub
    command:
      - ./start_server.sh
    ports:
      - "8000:8000"
    volumes:
      - ./src:/hub/src
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    container_name: pgadmin
    restart: on-failure
    depends_on:
      - postgres

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  pgadmin_data: { }