# Generated by Django 4.1.1 on 2022-09-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("volunteering", "0001_initial"),
        ("volunteering", "0002_alter_need_donation"),
        ("volunteering", "0003_need_city_opportunity_city_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="photo"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="price",
                    ),
                ),
                (
                    "donation",
                    models.URLField(blank=True, null=True, verbose_name="donation"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="photo"
                    ),
                ),
                (
                    "accounting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="volunteering.accounting",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="needs", to="volunteering.category"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="photo"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="opportunities", to="volunteering.category"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="city",
                    ),
                ),
            ],
        ),
    ]
