# Generated by Django 4.1.1 on 2022-11-10 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteering", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounting",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounting_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
