# Generated by Django 4.1.1 on 2022-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="category",
            field=models.ManyToManyField(related_name="opportunities", to="volunteering.category"),
        ),
    ]
