# Generated by Django 4.1.1 on 2022-11-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="need",
            name="photo",
            field=models.ImageField(
                default="needs/a692d4es-960.jpg", upload_to="needs/"
            ),
        ),
    ]
