# Generated by Django 4.1.1 on 2022-11-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0002_alter_accounting_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounting",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="need",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
