# Generated by Django 4.1.1 on 2022-11-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0002_alter_need_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="need",
            name="photo",
        ),
    ]
