# Generated by Django 4.1.1 on 2022-09-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0001_squashed_0003_need_city_opportunity_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="need",
            name="accounting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="needs",
                to="volunteering.accounting",
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="needs", to="volunteering.category"
            ),
        ),
    ]
