# Generated by Django 4.1.1 on 2022-11-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0003_remove_need_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounting",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/accounting/",
                verbose_name="photo",
            ),
        ),
        migrations.AddField(
            model_name="need",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/need/", verbose_name="photo"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/opportunity/",
                verbose_name="photo",
            ),
        ),
        migrations.AlterField(
            model_name="accounting",
            name="description",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="description",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="description",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="description"
            ),
        ),
    ]
