# Generated by Django 4.1.1 on 2022-09-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0004_alter_need_accounting_alter_need_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounting",
            name="description",
            field=models.TextField(max_length=256, verbose_name="description"),
        ),
    ]
