# Generated by Django 4.1.1 on 2022-09-27 16:27

import accounts.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("volunteering", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", accounts.managers.CustomerManager()),
            ],
        ),
        migrations.AddField(
            model_name="civilpersonprofile",
            name="need",
            field=models.ManyToManyField(to="volunteering.need"),
        ),
        migrations.AddField(
            model_name="civilpersonprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="militarypersonprofile",
            name="need",
            field=models.ManyToManyField(to="volunteering.need"),
        ),
        migrations.AddField(
            model_name="militarypersonprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="singlevolunteerprofile",
            name="opportunity",
            field=models.ManyToManyField(to="volunteering.opportunity"),
        ),
        migrations.AddField(
            model_name="singlevolunteerprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="volunteersorganisationprofile",
            name="opportunity",
            field=models.ManyToManyField(to="volunteering.opportunity"),
        ),
        migrations.AddField(
            model_name="volunteersorganisationprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
